FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY backend/backend.csproj ./
RUN dotnet restore

COPY backend/ .

RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends traceroute && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .
EXPOSE 5000

ENTRYPOINT ["dotnet", "backend.dll"]
