# build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY NetworkAgent/ ./NetworkAgent/
RUN dotnet publish NetworkAgent/NetworkAgent.csproj -c Release -o /app/publish

# runtime stage
FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /app
COPY --from=build /app/publish .

# ไม่ส่ง target ตอน container start
ENTRYPOINT ["dotnet", "NetworkAgent.dll"]
