<template>
  <div class="page-shell">
    <header class="page-header">
      <div>
        <p class="eyebrow">Alert queue</p>
        <h1>Active notifications</h1>
        <p class="text-muted">
          Review and acknowledge current alerts generated by latency, packet loss, and uptime
          monitors.
        </p>
      </div>
      <button class="btn-primary">Acknowledge all</button>
    </header>

    <section class="alerts-grid">
      <article class="panel alert-card" v-for="alert in alerts" :key="alert.id">
        <div class="alert-head">
          <span class="pill soft-pill">
            <span class="status-dot" :class="alert.statusClass"></span>
            {{ alert.severity }}
          </span>
          <span class="alert-time text-muted">{{ alert.time }}</span>
        </div>
        <h3>{{ alert.title }}</h3>
        <p class="text-muted">{{ alert.detail }}</p>
        <div class="alert-foot">
          <span>{{ alert.location }}</span>
          <button class="btn-ghost compact">Acknowledge</button>
        </div>
      </article>
    </section>
  </div>
</template>

<script setup>
const alerts = [
  {
    id: 1,
    severity: "Critical",
    statusClass: "status-danger",
    time: "2m ago",
    title: "Packet loss spike",
    detail: "Edge POP West exceeding 3% loss for last three samples.",
    location: "Los Angeles",
  },
  {
    id: 2,
    severity: "Warning",
    statusClass: "status-warning",
    time: "8m ago",
    title: "Elevated latency",
    detail: "Singapore path above 200 ms median since 11:00 UTC.",
    location: "Singapore",
  },
  {
    id: 3,
    severity: "Info",
    statusClass: "status-success",
    time: "15m ago",
    title: "Maintenance window",
    detail: "Planned work in London POP; monitoring in observe-only mode.",
    location: "London",
  },
];
</script>

<style scoped>
.page-shell {
  padding: 48px clamp(24px, 6vw, 72px);
  display: flex;
  flex-direction: column;
  gap: 28px;
}

.page-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 20px;
}

h1 {
  margin: 6px 0;
  font-size: clamp(28px, 4vw, 36px);
}

.alerts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 20px;
}

.alert-card {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.alert-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.alert-foot {
  display: flex;
  justify-content: space-between;
  align-items: center;
  color: var(--text-muted);
  font-size: 14px;
}

@media (max-width: 768px) {
  .page-header {
    flex-direction: column;
  }
}
</style>

